### ISSUE TITLE
Visual review for IBM Design Language

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/spongy#22]
@candidculture, please guide us in making sure Spongy's UI is aligned with the IBM Design Language:
![screen shot 2017-01-13 at 10 37 57 am](https://cloud.githubusercontent.com/assets/7519029/21937306/800e228e-d97c-11e6-9e90-49c3314a4e8a.png)

![spongy](https://cloud.githubusercontent.com/assets/7519029/21937310/8866bd4c-d97c-11e6-98c4-87ee7a3a2fc6.gif)

If there are any major recommendations for change, please include a mock-up. Thanks!

**Comment by diego-codes** [comment]
Also I have a UI question, the eye dropper has some built-in tolerance that allows the user to sample a color that might be slightly off (sometimes due to JPEG encoding) and still get the brand color that should be used in the design. See example:

> The color on the JPEG is slightly off but it still returns the right brand color: <br/> 
<img width="390" alt="screen shot 2017-01-13 at 2 06 10 pm" src="https://cloud.githubusercontent.com/assets/5973294/21944122/1290cdf6-d99a-11e6-8b14-740e5d4400d6.png">


My question is should the hex value on the eye dropper tool display the true color of the pixel that is being sampled (in this case #E6E8F5) or what the brand color hex value is (#E7E9F7)?

**Comment by seejamescode** [comment]
Maybe some natural language in there?

 "Similar to {palette hex}" and "Exactly {palette hex}"

**Comment by diego-codes** [comment]
Like this?

![screen shot 2017-01-13 at 3 13 03 pm](https://cloud.githubusercontent.com/assets/5973294/21945783/e17b35fe-d9a2-11e6-96a5-ba54fa83ebb1.png)

**Comment by seejamescode** [comment]
💯 , but @candidculture is the final judge

**Comment by diego-codes** [comment]
@candidculture, do you have any feedback on the UI? I'm going to be taking screenshots for the content that will be written for this and I'd love include any changes you suggest.

**Comment by Candidculture** [comment]
Visually i think it looks pretty good, but the type could use some work. a few things
1. Does the color need to show up in a text box? is that just so it can be copy and pasted? it seems a little jarring.
2. are the margins the same on top and bottom? doesn't look to be - and show be if not.
3. I like the hex aligned left like shown in the mocks, but isn't the case in the app i downloaded. 

4. My biggest recommendation would be fore you to mimic the type on the Design language site as is. It shows better hierarchy and emphasizes the Name (using size and weight) which seems sitting as the whole point to the app is to showcase the name, not the hex, right?

![e17b35fe-d9a2-11e6-96a5-ba54fa83ebb1-01](https://cloud.githubusercontent.com/assets/25105397/22128032/4cfb4524-de64-11e6-809a-ade324194976.png)

**Comment by Candidculture** [comment]
^^^ @cuyaproductions

**Comment by diego-codes** [comment]
Thanks for your feedback, @Candidculture:

1. The text box is there to allow the user to copy and paste the brand color information in the format that FEDs would need to use in their Sass files. I changed it up so that it doesn't look like a text box any more, but can still allow for copying and pasting:
![screen shot 2017-01-22 at 6 00 54 pm](https://cloud.githubusercontent.com/assets/5973294/22187478/bf901cb2-e0cc-11e6-97e0-534ddc2e8567.png)

2. Fixed the margins.

3. I fixed the left alignment issue... I think. It's hard to test this because the styling of any given website can override this alignment, but I think I made it so that it's not easy to override. Let me know if you still find this issue and what site it was on.

4. Mimicked type hierarchy from colors site:
![screen shot 2017-01-22 at 5 54 54 pm](https://cloud.githubusercontent.com/assets/5973294/22187512/99ae7844-e0cd-11e6-9c08-b4b5f4bbb08e.png)

What are your thoughts on displaying hex and rgb values of the actual pixel that was sampled (which could be slightly off from the brand color) vs just displaying the rgb and hex values from the actual brand color?

**Comment by seejamescode** [comment]
> What are your thoughts on displaying hex and rgb values of the actual pixel that was sampled (which could be slightly off from the brand color) vs just displaying the rgb and hex values from the actual brand color?

I believe it should only display the actual pixel color if no similar match is found.

**Comment by Candidculture** [comment]
lookin good, and i agree with James - even if a little dis honest
